### ISSUE TITLE
Future proof Django version instalation command

### ISSUE THREAD

**Issue by soutys** [ggcarrots/django-carrots#26]
Why not:
`pip install "Django>=1.6,<1.7"`
?
Is version bumping better somehow?

**Comment by qrees** [comment]
I think that:
`pip install "Django==1.6.4"`
is easier to understand. It is also a good practice for production code.

Maybe you have some time to check if the tutorial works with Django 1.7?

**Comment by soutys** [comment]
With Django 1.7.2 all samples work. Changes/problems? Only minor:
- slightly different output messages and SQLite DB filename;
- `syncdb` needs `makemigrations` step;
- few minor things should be updated (i.e. dates/years, result/final `models.py` content);
