### ISSUE TITLE
Directions for updating Python on Mac

### ISSUE THREAD

**Issue by sguermond** [ggcarrots/django-carrots#43]
(add all this to install.rst)

OSX does not automatically replace all system links to Python 3.

Instructions can be found [here](http://wolfpaulus.com/jounal/mac/installing_python_osx/).
The last step is to replace local (``which python``) with a symbolic link to ``/usr/bin/python``:

```
sudo rm /usr/local/bin/python
sudo ln -s /usr/bin/python /usr/local/bin/python
```

The correct version of Python should now be the default when you run ``python``.

**Comment by qrees** [comment]
I don't think replacing python version globally in the system is a good idea. That's why we virtualenv, so that there can be multiple versions of python.
